Rework test wrapper

diff --git a/scripts/run_test b/scripts/run_test
--- a/scripts/run_test
+++ b/scripts/run_test
@@ -1,5 +1,14 @@
 #!/bin/bash
 
+pipenv install
+
+echo "-> Test ansible"
+if ! pipenv run ansible --version ; then
+    echo "---> Ansible failed to run"
+    echo "---> Reinstall SELinux libraries"
+    pipenv run pip uninstall selinux -y; pipenv install
+fi
+
 for VARIABLE in $(echo "$1" | sed 's/#/ /g')
 do
     export $VARIABLE
@@ -10,4 +19,4 @@ if [ -n "$SCENARIO" ] ; then
     SCENARIO="-s $SCENARIO"
 fi
 
-molecule test $SCENARIO
+pipenv run molecule test $SCENARIO
